### ISSUE TITLE
Pripravit meetup v Brne

### ISSUE THREAD

**Issue by radimklaska** [Drupalcz/community#1]
~~Pokud bychom chteli~~ meetup kazdy mesic a stridat Praha / Brno, ~~tak to vychazi nekdy po 20.7.~~
- ~~chceme vubec meetup v cervenci? - nebude lepsi pockat do rijen? (zari=Praha meetup, rijen=Brno meetup, listopad=Praha Ironcamp)~~
- misto konani?
- mistni organizatori?

**Comment by miloskroulik** [comment]
Zeptám se ve firmě (P&R), jestli by o pořádání byl zájem a dám vědět.

**Comment by radimklaska** [comment]
Zajem je, uz jsem s par lidmi z P&R mluvil v Bratislave :-) Meli bychom bajit nejake misto - cowork, neci kancelare...
